'\" p
.TH "vtep" 5 " DB Schema 1.3.0" "Open vSwitch 2.3.0" "Open vSwitch Manual"
.\" -*- nroff -*-
.de TQ
.  br
.  ns
.  TP "\\$1"
..
.de ST
.  PP
.  RS -0.15in
.  I "\\$1"
.  RE
..
.SH NAME
hardware_vtep \- hardware_vtep database schema
.PP
This schema specifies relations that a VTEP can use to integrate
physical ports into logical switches maintained by a network
virtualization controller such as NSX.
.PP
Glossary:
.RS
.TP
VTEP
VXLAN Tunnel End Point, an entity which originates and/or terminates
VXLAN tunnels.
.TP
HSC
Hardware Switch Controller.
.TP
NVC
Network Virtualization Controller, e.g. NSX.
.TP
VRF
Virtual Routing and Forwarding instance.
.RE
.SH "TABLE SUMMARY"
.PP
The following list summarizes the purpose of each of the tables in the
\fBhardware_vtep\fR database.  Each table is described in more detail on a later
page.
.IP "Table" 1in
Purpose
.TQ 1in
\fBGlobal\fR
Top-level configuration.
.TQ 1in
\fBManager\fR
OVSDB management connection.
.TQ 1in
\fBPhysical_Switch\fR
A physical switch.
.TQ 1in
\fBTunnel\fR
A tunnel created by a physical switch.
.TQ 1in
\fBPhysical_Port\fR
A port within a physical switch.
.TQ 1in
\fBLogical_Binding_Stats\fR
Statistics for a VLAN on a physical port bound to a logical network.
.TQ 1in
\fBLogical_Switch\fR
A layer\-2 domain.
.TQ 1in
\fBUcast_Macs_Local\fR
Unicast MACs (local)
.TQ 1in
\fBUcast_Macs_Remote\fR
Unicast MACs (remote)
.TQ 1in
\fBMcast_Macs_Local\fR
Multicast MACs (local)
.TQ 1in
\fBMcast_Macs_Remote\fR
Multicast MACs (remote)
.TQ 1in
\fBLogical_Router\fR
A logical L3 router.
.TQ 1in
\fBArp_Sources_Local\fR
ARP source addresses for logical routers
.TQ 1in
\fBArp_Sources_Remote\fR
ARP source addresses for logical routers
.TQ 1in
\fBPhysical_Locator_Set\fR
Physical_Locator_Set configuration.
.TQ 1in
\fBPhysical_Locator\fR
Physical_Locator configuration.
.\" check if in troff mode (TTY)
.if t \{
.bp
.SH "TABLE RELATIONSHIPS"
.PP
The following diagram shows the relationship among tables in the
database.  Each node represents a table.  Tables that are part of the
``root set'' are shown with double borders.  Each edge leads from the
table that contains it and points to the table that its value
represents.  Edges are labeled with their column names, followed by a
constraint on the number of allowed values: \fB?\fR for zero or one,
\fB*\fR for zero or more, \fB+\fR for one or more.  Thick lines
represent strong references; thin lines represent weak references.
.RS -1in
.ps -3
.PS
linethick = 1;
linethick = 0.5;
box at 1.523496279,2.052164564 wid 0.953055436 height 0.250435 "Mcast_Macs_Remote"
box at 1.523496279,2.052164564 wid 0.897499880444445 height 0.194879444444444
linethick = 1;
box at 3.151323779,2.949573343 wid 0.93913125 height 0.250435 "Physical_Locator_Set"
linethick = 0.5;
box at 5.23809846,1.119995407 wid 0.709582529 height 0.250435 "Logical_Switch"
box at 5.23809846,1.119995407 wid 0.654026973444444 height 0.194879444444444
linethick = 0.5;
box at 3.151323779,2.170419971 wid 0.848674128 height 0.250435 "Ucast_Macs_Local"
box at 3.151323779,2.170419971 wid 0.793118572444444 height 0.194879444444444
linethick = 1;
box at 5.23809846,2.914762878 wid 0.772191279 height 0.250435 "Physical_Locator"
linethick = 1;
box at 3.151323779,2.573920843 wid 0.3826095843 height 0.250435 "Tunnel"
linethick = 0.5;
box at 0.18782625,0.542592471 wid 0.3756525 height 0.250435 "Global"
box at 0.18782625,0.542592471 wid 0.320096944444444 height 0.194879444444444
linethick = 1;
box at 1.523496279,0.751305 wid 0.744342907 height 0.250435 "Physical_Switch"
linethick = 1;
box at 1.523496279,0.3756525 wid 0.4521754186 height 0.250435 "Manager"
linethick = 1;
box at 3.151323779,0.2643491686 wid 0.640011686 height 0.250435 "Physical_Port"
linethick = 0.5;
box at 3.151323779,0.640011686 wid 0.702620436 height 0.250435 "Logical_Router"
box at 3.151323779,0.640011686 wid 0.647064880444445 height 0.194879444444444
linethick = 0.5;
box at 1.523496279,1.349544128 wid 0.869560407 height 0.250435 "Mcast_Macs_Local"
box at 1.523496279,1.349544128 wid 0.814004851444444 height 0.194879444444444
linethick = 0.5;
box at 3.151323779,1.780893372 wid 0.932169157 height 0.250435 "Ucast_Macs_Remote"
box at 3.151323779,1.780893372 wid 0.876613601444444 height 0.194879444444444
linethick = 0.5;
box at 3.151323779,3.874780407 wid 0.953055436 height 0.250435 "Arp_Sources_Remote"
box at 3.151323779,3.874780407 wid 0.897499880444445 height 0.194879444444444
linethick = 0.5;
box at 3.151323779,3.499127907 wid 0.869560407 height 0.250435 "Arp_Sources_Local"
box at 3.151323779,3.499127907 wid 0.814004851444444 height 0.194879444444444
linethick = 1;
box at 5.23809846,0.1252175 wid 0.980853721 height 0.250435 "Logical_Binding_Stats"
linethick = 1;
spline -> from 1.659833093,2.178133369 to 1.659833093,2.178133369 to 1.777637717,2.282414503 to 1.955697002,2.429570109 to 2.1286975,2.532198372 to 2.353888652,2.665780401 to 2.428768717,2.663025616 to 2.671289971,2.761747093 to 2.721026362,2.781982241 to 2.77381806,2.803068868 to 2.825507844,2.823454277
"locator_set" at 2.337410029,2.772165189
linethick = 1;
spline -> from 1.619412884,1.926195759 to 1.619412884,1.926195759 to 1.72750063,1.794466949 to 1.916078185,1.593618079 to 2.1286975,1.495647907 to 2.374374235,1.3824012 to 4.117101313,1.218216014 to 4.88097815,1.150748825
"logical_switch" at 3.151323779,1.443457253
linethick = 1;
spline -> from 3.622742623,3.038878464 to 3.622742623,3.038878464 to 3.667820923,3.044989078 to 3.71294931,3.050198126 to 3.756525,3.053904564 to 4.138488462,3.086611375 to 4.238111505,3.096177992 to 4.619123314,3.053904564 to 4.694704597,3.045540035 to 4.774493188,3.031565762 to 4.850775689,3.015638096
"locators+" at 4.187824157,3.147817689
linethick = 1;
spline -> from 3.577814584,2.086975029 to 3.577814584,2.086975029 to 3.63781881,2.075304758 to 3.698724602,2.063434139 to 3.756525,2.052164564 to 4.139840811,1.977635108 to 4.284391893,2.086273811 to 4.619123314,1.885224593 to 4.879876236,1.728602544 to 5.07731919,1.419816189 to 5.17348623,1.246214647
"logical_switch" at 4.187824157,2.118279404
linethick = 1;
spline -> from 3.577263627,2.196765733 to 3.577263627,2.196765733 to 3.943048988,2.224463844 to 4.439010462,2.275702845 to 4.619123314,2.358246221 to 4.834597588,2.457017785 to 5.02823393,2.65761622 to 5.13942707,2.789094595
"locator" at 4.187824157,2.424361061
linethick = 1;
spline -> from 3.345010208,2.644793948 to 3.345010208,2.644793948 to 3.46251431,2.685063896 to 3.616431661,2.733047242 to 3.756525,2.761747093 to 4.123913145,2.83692768 to 4.550454037,2.876045627 to 4.851326646,2.895829992
"remote" at 4.187824157,2.939155247
linethick = 1;
spline -> from 3.344859947,2.550580301 to 3.344859947,2.550580301 to 3.629103672,2.522281146 to 4.173899971,2.491127032 to 4.619123314,2.601719128 to 4.771087272,2.639484726 to 4.928360452,2.719623926 to 5.04626525,2.789395117
"local" at 4.187824157,2.667833968
linethick = 1;
spline -> from 0.3763587267,0.572043627 to 0.3763587267,0.572043627 to 0.576250935,0.603297915 to 0.897258518,0.653485089 to 1.148945693,0.692803384
"switches*" at 0.709582529,0.713038532
linethick = 1;
spline -> from 0.3770349012,0.4603095474 to 0.3770349012,0.4603095474 to 0.4172297187,0.4459095349 to 0.4599088514,0.4328368279 to 0.50087,0.4243470814 to 0.769737016,0.3686102678 to 1.086537291,0.3624145059 to 1.295500255,0.3662611875
"managers*" at 0.709582529,0.4904368779
linethick = 1;
spline -> from 1.694092601,0.877373979 to 1.694092601,0.877373979 to 1.790960859,0.953606393 to 1.910969311,1.056234656 to 2.00348,1.161717878 to 2.295236775,1.494445819 to 2.351684824,1.598977388 to 2.546072471,1.996517907 to 2.620802275,2.149383431 to 2.556490567,2.232728199 to 2.671289971,2.358246221 to 2.747171776,2.441190293 to 2.860919353,2.494182339 to 2.958689177,2.52688915
"tunnels*" at 2.337410029,2.062632747
linethick = 1;
spline -> from 1.896944951,0.63961099 to 1.896944951,0.63961099 to 2.178534065,0.555364656 to 2.560798049,0.4410010089 to 2.829064021,0.3607466088
"ports*" at 2.337410029,0.636505596
linethick = 1;
spline -> from 3.472732058,0.2533099938 to 3.472732058,0.2533099938 to 3.782770588,0.2556590741 to 4.257044391,0.2942761511 to 4.619123314,0.4799987471 to 4.852979517,0.599942086 to 5.04927047,0.842813949 to 5.15495404,0.992473905
"vlan_bindings value*" at 4.187824157,0.546098561
linethick = 1;
spline -> from 3.472732058,0.1810044006 to 3.472732058,0.1810044006 to 3.563840311,0.1609846267 to 3.663513441,0.1424324019 to 3.756525,0.1321745843 to 4.08509572,0.0959316311 to 4.457141956,0.0943238384 to 4.74624412,0.1017066622
"vlan_stats value*" at 4.187824157,0.1982593721
linethick = 1;
spline -> from 3.502934519,0.636455509 to 3.502934519,0.636455509 to 3.80510939,0.642465949 to 4.24938108,0.672968932 to 4.619123314,0.786065378 to 4.7732911,0.833247332 to 4.93306863,0.920548973 to 5.05177482,0.994076689
"switch_binding value*" at 4.187824157,0.852180218
linethick = 1;
spline -> from 1.665693272,1.476364412 to 1.665693272,1.476364412 to 1.769473536,1.574484845 to 1.908064265,1.7179841 to 2.00348,1.864338314 to 2.08061398,1.982693895 to 2.032480373,2.053116217 to 2.1286975,2.156545872 to 2.27094458,2.309411396 to 2.41118818,2.212793573 to 2.546072471,2.372170407 to 2.663576573,2.510961484 to 2.546773689,2.629216891 to 2.671289971,2.761747093 to 2.693378338,2.785237896 to 2.71872236,2.805823653 to 2.746019775,2.823854973
"locator_set" at 2.337410029,2.438285247
linethick = 1;
spline -> from 1.959002744,1.238100553 to 1.959002744,1.238100553 to 2.172173016,1.189115467 to 2.433476895,1.137275422 to 2.671289971,1.113033314 to 3.457155001,1.032944201 to 4.385367285,1.067103535 to 4.882080064,1.095703212
"logical_switch" at 3.151323779,1.179148154
linethick = 1;
spline -> from 3.451244735,1.654573958 to 3.451244735,1.654573958 to 3.512150527,1.625373237 to 3.574859451,1.592716513 to 3.6313075,1.558256657 to 3.691512074,1.521542886 to 3.692213292,1.489737641 to 3.756525,1.460887529 to 4.112192787,1.301109999 to 4.239814463,1.391216512 to 4.619123314,1.300859564 to 4.70517278,1.280373981 to 4.797082425,1.255280394 to 4.883031717,1.230437242
"logical_switch" at 4.187824157,1.526952282
linethick = 1;
spline -> from 3.617433401,1.708617831 to 3.617433401,1.708617831 to 3.982968327,1.661936747 to 4.456190303,1.62632489 to 4.619123314,1.725196628 to 5.00920087,1.961957877 to 5.16497144,2.533500634 to 5.21656105,2.788393377
"locator" at 4.187824157,1.791311468
linethick = 1;
spline -> from 3.630205586,3.857600566 to 3.630205586,3.857600566 to 3.930527238,3.829101063 to 4.316698008,3.758778915 to 4.619123314,3.589585029 to 4.857787869,3.456053087 to 5.05528091,3.197303645 to 5.158961,3.041933771
"locator" at 4.187824157,3.906084782
linethick = 1;
spline -> from 3.587331114,3.458757785 to 3.587331114,3.458757785 to 3.884096589,3.422645058 to 4.282538674,3.356930914 to 4.619123314,3.241730814 to 4.766329007,3.191343292 to 4.921147924,3.109601308 to 5.03925307,3.040481248
"locator" at 4.187824157,3.495671904
.ps +3
.PE
.RE\}
.bp
.SH "Global TABLE"
Top-level configuration for a hardware VTEP.  There must be
exactly one record in the \fBGlobal\fR table.
.SS "Summary:
.TQ 3.00in
\fBswitches\fR
set of \fBPhysical_Switch\fRs
.TQ .25in
\fIDatabase Configuration:\fR
.RS .25in
.TQ 2.75in
\fBmanagers\fR
set of \fBManager\fRs
.RE
.SS "Details:
.IP "\fBswitches\fR: set of \fBPhysical_Switch\fRs"
The physical switches managed by the VTEP.
.ST "Database Configuration:"
These columns primarily configure the database server
(\fBovsdb\-server\fR), not the hardware VTEP itself.
.IP "\fBmanagers\fR: set of \fBManager\fRs"
Database clients to which the database server should connect or
to which it should listen, along with options for how these
connection should be configured.  See the \fBManager\fR
table for more information.
.bp
.SH "Manager TABLE"
Configuration for a database connection to an Open vSwitch Database
(OVSDB) client.
.PP
The database server can initiate and maintain active connections
to remote clients.  It can also listen for database connections.
.SS "Summary:
.TQ .25in
\fICore Features:\fR
.RS .25in
.TQ 2.75in
\fBtarget\fR
string (must be unique within table)
.RE
.TQ .25in
\fIClient Failure Detection and Handling:\fR
.RS .25in
.TQ 2.75in
\fBmax_backoff\fR
optional integer, at least 1,000
.TQ 2.75in
\fBinactivity_probe\fR
optional integer
.RE
.TQ .25in
\fIStatus:\fR
.RS .25in
.TQ 2.75in
\fBis_connected\fR
boolean
.TQ 2.75in
\fBstatus : last_error\fR
optional string
.TQ 2.75in
\fBstatus : state\fR
optional string, one of \fBACTIVE\fR, \fBVOID\fR, \fBCONNECTING\fR, \fBIDLE\fR, or \fBBACKOFF\fR
.TQ 2.75in
\fBstatus : sec_since_connect\fR
optional string, containing an integer, at least 0
.TQ 2.75in
\fBstatus : sec_since_disconnect\fR
optional string, containing an integer, at least 0
.TQ 2.75in
\fBstatus : locks_held\fR
optional string
.TQ 2.75in
\fBstatus : locks_waiting\fR
optional string
.TQ 2.75in
\fBstatus : locks_lost\fR
optional string
.TQ 2.75in
\fBstatus : n_connections\fR
optional string, containing an integer, at least 2
.RE
.TQ .25in
\fIConnection Parameters:\fR
.RS .25in
.TQ 2.75in
\fBother_config : dscp\fR
optional string, containing an integer
.RE
.SS "Details:
.ST "Core Features:"
.IP "\fBtarget\fR: string (must be unique within table)"
Connection method for managers.
.IP
The following connection methods are currently supported:
.RS
.TP
\fBssl:\fIip\fB\fR[\fB:\fIport\fB\fR]
The specified SSL \fIport\fR (default: 6632) on the host at
the given \fIip\fR, which must be expressed as an IP address
(not a DNS name).
.IP
SSL key and certificate configuration happens outside the
database.
.TP
\fBtcp:\fIip\fB\fR[\fB:\fIport\fB\fR]
The specified TCP \fIport\fR (default: 6632) on the host at
the given \fIip\fR, which must be expressed as an IP address
(not a DNS name).
.TP
\fBpssl:\fR[\fIport\fR][\fB:\fIip\fB\fR]
Listens for SSL connections on the specified TCP \fIport\fR
(default: 6632).  If \fIip\fR, which must be expressed as an
IP address (not a DNS name), is specified, then connections are
restricted to the specified local IP address.
.TP
\fBptcp:\fR[\fIport\fR][\fB:\fIip\fB\fR]
Listens for connections on the specified TCP \fIport\fR
(default: 6632).  If \fIip\fR, which must be expressed as an
IP address (not a DNS name), is specified, then connections are
restricted to the specified local IP address.
.RE
.ST "Client Failure Detection and Handling:"
.IP "\fBmax_backoff\fR: optional integer, at least 1,000"
Maximum number of milliseconds to wait between connection attempts.
Default is implementation-specific.
.IP "\fBinactivity_probe\fR: optional integer"
Maximum number of milliseconds of idle time on connection to the
client before sending an inactivity probe message.  If the Open
vSwitch database does not communicate with the client for the
specified number of seconds, it will send a probe.  If a
response is not received for the same additional amount of time,
the database server assumes the connection has been broken
and attempts to reconnect.  Default is implementation-specific.
A value of 0 disables inactivity probes.
.ST "Status:"
.IP "\fBis_connected\fR: boolean"
\fBtrue\fR if currently connected to this manager,
\fBfalse\fR otherwise.
.IP "\fBstatus : last_error\fR: optional string"
A human-readable description of the last error on the connection
to the manager; i.e. \fBstrerror(errno)\fR\.  This key
will exist only if an error has occurred.
.IP "\fBstatus : state\fR: optional string, one of \fBACTIVE\fR, \fBVOID\fR, \fBCONNECTING\fR, \fBIDLE\fR, or \fBBACKOFF\fR"
The state of the connection to the manager:
.RS
.TP
\fBVOID\fR
Connection is disabled.
.TP
\fBBACKOFF\fR
Attempting to reconnect at an increasing period.
.TP
\fBCONNECTING\fR
Attempting to connect.
.TP
\fBACTIVE\fR
Connected, remote host responsive.
.TP
\fBIDLE\fR
Connection is idle.  Waiting for response to keep-alive.
.RE
.IP
These values may change in the future.  They are provided only for
human consumption.
.IP "\fBstatus : sec_since_connect\fR: optional string, containing an integer, at least 0"
The amount of time since this manager last successfully connected
to the database (in seconds). Value is empty if manager has never
successfully connected.
.IP "\fBstatus : sec_since_disconnect\fR: optional string, containing an integer, at least 0"
The amount of time since this manager last disconnected from the
database (in seconds). Value is empty if manager has never
disconnected.
.IP "\fBstatus : locks_held\fR: optional string"
Space-separated list of the names of OVSDB locks that the connection
holds.  Omitted if the connection does not hold any locks.
.IP "\fBstatus : locks_waiting\fR: optional string"
Space-separated list of the names of OVSDB locks that the connection is
currently waiting to acquire.  Omitted if the connection is not waiting
for any locks.
.IP "\fBstatus : locks_lost\fR: optional string"
Space-separated list of the names of OVSDB locks that the connection
has had stolen by another OVSDB client.  Omitted if no locks have been
stolen from this connection.
.IP "\fBstatus : n_connections\fR: optional string, containing an integer, at least 2"
When \fBtarget\fR specifies a connection method that
listens for inbound connections (e.g. \fBptcp:\fR or
\fBpssl:\fR) and more than one connection is actually active,
the value is the number of active connections.  Otherwise, this
key-value pair is omitted.
.IP
When multiple connections are active, status columns and key-value
pairs (other than this one) report the status of one arbitrarily
chosen connection.
.ST "Connection Parameters:"
Additional configuration for a connection between the manager
and the database server.
.IP "\fBother_config : dscp\fR: optional string, containing an integer"
The Differentiated Service Code Point (DSCP) is specified using 6 bits
in the Type of Service (TOS) field in the IP header. DSCP provides a
mechanism to classify the network traffic and provide Quality of
Service (QoS) on IP networks.
The DSCP value specified here is used when establishing the
connection between the manager and the database server.  If no
value is specified, a default value of 48 is chosen.  Valid DSCP
values must be in the range 0 to 63.
.bp
.SH "Physical_Switch TABLE"
A physical switch that implements a VTEP.
.SS "Summary:
.TQ 3.00in
\fBports\fR
set of \fBPhysical_Port\fRs
.TQ 3.00in
\fBtunnels\fR
set of \fBTunnel\fRs
.TQ .25in
\fINetwork Status:\fR
.RS .25in
.TQ 2.75in
\fBmanagement_ips\fR
set of strings
.TQ 2.75in
\fBtunnel_ips\fR
set of strings
.RE
.TQ .25in
\fIIdentification:\fR
.RS .25in
.TQ 2.75in
\fBname\fR
string (must be unique within table)
.TQ 2.75in
\fBdescription\fR
string
.RE
.TQ .25in
\fIError Notification:\fR
.RS .25in
.TQ 2.75in
\fBswitch_fault_status : mac_table_exhaustion\fR
none
.TQ 2.75in
\fBswitch_fault_status : tunnel_exhaustion\fR
none
.TQ 2.75in
\fBswitch_fault_status : unspecified_fault\fR
none
.RE
.SS "Details:
.IP "\fBports\fR: set of \fBPhysical_Port\fRs"
The physical ports within the switch.
.IP "\fBtunnels\fR: set of \fBTunnel\fRs"
Tunnels created by this switch as instructed by the NVC.
.ST "Network Status:"
.IP "\fBmanagement_ips\fR: set of strings"
IPv4 or IPv6 addresses at which the switch may be contacted
for management purposes.
.IP "\fBtunnel_ips\fR: set of strings"
IPv4 or IPv6 addresses on which the switch may originate or
terminate tunnels.
.IP
This column is intended to allow a \fBManager\fR to
determine the \fBPhysical_Switch\fR that terminates
the tunnel represented by a \fBPhysical_Locator\fR\.
.ST "Identification:"
.IP "\fBname\fR: string (must be unique within table)"
Symbolic name for the switch, such as its hostname.
.IP "\fBdescription\fR: string"
An extended description for the switch, such as its switch login
banner.
.ST "Error Notification:"
An entry in this column indicates to the NVC that this switch
has encountered a fault. The switch must clear this column
when the fault has been cleared.
.IP "\fBswitch_fault_status : mac_table_exhaustion\fR: none"
Indicates that the switch has been unable to process MAC
entries requested by the NVC due to lack of table resources.
.IP "\fBswitch_fault_status : tunnel_exhaustion\fR: none"
Indicates that the switch has been unable to create tunnels
requested by the NVC due to lack of resources.
.IP "\fBswitch_fault_status : unspecified_fault\fR: none"
Indicates that an error has occurred in the switch but that no
more specific information is available.
.bp
.SH "Tunnel TABLE"
A tunnel created by a \fBPhysical_Switch\fR\.
.SS "Summary:
.TQ 3.00in
\fBlocal\fR
\fBPhysical_Locator\fR
.TQ 3.00in
\fBremote\fR
\fBPhysical_Locator\fR
.TQ .25in
\fIBidirectional Forwarding Detection (BFD):\fR
.RS .25in
.TQ .25in
\fIBFD Local Configuration:\fR
.RS .25in
.TQ 2.50in
\fBbfd_config_local : bfd_dst_mac\fR
optional string
.TQ 2.50in
\fBbfd_config_local : bfd_dst_ip\fR
optional string
.RE
.TQ .25in
\fIBFD Remote Configuration:\fR
.RS .25in
.TQ 2.50in
\fBbfd_config_remote : bfd_dst_mac\fR
optional string
.TQ 2.50in
\fBbfd_config_remote : bfd_dst_ip\fR
optional string
.RE
.TQ .25in
\fIBFD Parameters:\fR
.RS .25in
.TQ 2.50in
\fBbfd_params : enable\fR
optional string, either \fBtrue\fR or \fBfalse\fR
.TQ 2.50in
\fBbfd_params : min_rx\fR
optional string, containing an integer, at least 1
.TQ 2.50in
\fBbfd_params : min_tx\fR
optional string, containing an integer, at least 1
.TQ 2.50in
\fBbfd_params : decay_min_rx\fR
optional string, containing an integer
.TQ 2.50in
\fBbfd_params : forwarding_if_rx\fR
optional string, either \fBtrue\fR or \fBfalse\fR
.TQ 2.50in
\fBbfd_params : cpath_down\fR
optional string, either \fBtrue\fR or \fBfalse\fR
.TQ 2.50in
\fBbfd_params : check_tnl_key\fR
optional string, either \fBtrue\fR or \fBfalse\fR
.RE
.TQ .25in
\fIBFD Status:\fR
.RS .25in
.TQ 2.50in
\fBbfd_status : state\fR
optional string, one of \fBdown\fR, \fBinit\fR, \fBup\fR, or \fBadmin_down\fR
.TQ 2.50in
\fBbfd_status : forwarding\fR
optional string, either \fBtrue\fR or \fBfalse\fR
.TQ 2.50in
\fBbfd_status : diagnostic\fR
optional string
.TQ 2.50in
\fBbfd_status : remote_state\fR
optional string, one of \fBdown\fR, \fBinit\fR, \fBup\fR, or \fBadmin_down\fR
.TQ 2.50in
\fBbfd_status : remote_diagnostic\fR
optional string
.RE
.RE
.SS "Details:
.IP "\fBlocal\fR: \fBPhysical_Locator\fR"
Tunnel end-point local to the physical switch.
.IP "\fBremote\fR: \fBPhysical_Locator\fR"
Tunnel end-point remote to the physical switch.
.ST "Bidirectional Forwarding Detection (BFD):"
BFD, defined in RFC 5880, allows point to point detection of
connectivity failures by occasional transmission of BFD control
messages. VTEPs are expected to implement BFD.
.PP
BFD operates by regularly transmitting BFD control messages at a
rate negotiated independently in each direction.  Each endpoint
specifies the rate at which it expects to receive control messages,
and the rate at which it\(cqs willing to transmit them.  An endpoint
which fails to receive BFD control messages for a period of three
times the expected reception rate will signal a connectivity
fault.  In the case of a unidirectional connectivity issue, the
system not receiving BFD control messages will signal the problem
to its peer in the messages it transmits.
.PP
A hardware VTEP is expected to use BFD to determine reachability of
devices at the end of the tunnels with which it exchanges data. This
can enable the VTEP to choose a functioning service node among a set of
service nodes providing high availability. It also enables the NVC to
report the health status of tunnels.
.PP
In most cases the BFD peer of a hardware VTEP will be an Open vSwitch
instance. The Open vSwitch implementation of BFD aims to comply
faithfully with the requirements put forth in RFC 5880.  Open vSwitch
does not implement the optional Authentication or ``Echo Mode\(cq\(cq
features.
.ST "BFD Local Configuration:"
The HSC writes the key-value pairs in the
\fBbfd_config_local\fR column to specifiy the local
configurations to be used for BFD sessions on this tunnel.
.IP "\fBbfd_config_local : bfd_dst_mac\fR: optional string"
Set to an Ethernet address in the form
\fIxx\fR:\fIxx\fR:\fIxx\fR:\fIxx\fR:\fIxx\fR:\fIxx\fR
to set the MAC expected as destination for received BFD packets.
.IP "\fBbfd_config_local : bfd_dst_ip\fR: optional string"
Set to an IPv4 address to set the IP address that is expected as destination
for received BFD packets.  The default is \fB169.254.1.0\fR\.
.ST "BFD Remote Configuration:"
The \fBbfd_config_remote\fR column is the remote
counterpart of the \fBbfd_config_local\fR column.
The NVC writes the key-value pairs in this column.
.IP "\fBbfd_config_remote : bfd_dst_mac\fR: optional string"
Set to an Ethernet address in the form
\fIxx\fR:\fIxx\fR:\fIxx\fR:\fIxx\fR:\fIxx\fR:\fIxx\fR
to set the destination MAC to be used for transmitted BFD packets.
The default is \fB00:23:20:00:00:01\fR\.
.IP "\fBbfd_config_remote : bfd_dst_ip\fR: optional string"
Set to an IPv4 address to set the IP address used as destination
for transmitted BFD packets.  The default is \fB169.254.1.1\fR\.
.ST "BFD Parameters:"
The NVC sets up key-value pairs in the \fBbfd_params\fR
column to enable and configure BFD.
.IP "\fBbfd_params : enable\fR: optional string, either \fBtrue\fR or \fBfalse\fR"
True to enable BFD on this tunnel.
.IP "\fBbfd_params : min_rx\fR: optional string, containing an integer, at least 1"
The shortest interval, in milliseconds, at which this BFD session
offers to receive BFD control messages.  The remote endpoint may
choose to send messages at a slower rate.  Defaults to
\fB1000\fR\.
.IP "\fBbfd_params : min_tx\fR: optional string, containing an integer, at least 1"
The shortest interval, in milliseconds, at which this BFD session is
willing to transmit BFD control messages.  Messages will actually be
transmitted at a slower rate if the remote endpoint is not willing to
receive as quickly as specified.  Defaults to \fB100\fR\.
.IP "\fBbfd_params : decay_min_rx\fR: optional string, containing an integer"
An alternate receive interval, in milliseconds, that must be greater
than or equal to \fBbfd:min_rx\fR\.  The
implementation switches from \fBbfd:min_rx\fR to \fBbfd:decay_min_rx\fR when there is no obvious incoming
data traffic at the interface, to reduce the CPU and bandwidth cost
of monitoring an idle interface.  This feature may be disabled by
setting a value of 0.  This feature is reset whenever \fBbfd:decay_min_rx\fR or \fBbfd:min_rx\fR
changes.
.IP "\fBbfd_params : forwarding_if_rx\fR: optional string, either \fBtrue\fR or \fBfalse\fR"
True to consider the interface capable of packet I/O as long as it
continues to receive any packets (not just BFD packets).  This
prevents link congestion that causes consecutive BFD control packets
to be lost from marking the interface down.
.IP "\fBbfd_params : cpath_down\fR: optional string, either \fBtrue\fR or \fBfalse\fR"
Set to true to notify the remote endpoint that traffic should not be
forwarded to this system for some reason other than a connectivty
failure on the interface being monitored.  The typical underlying
reason is ``concatenated path down,\(cq\(cq that is, that connectivity
beyond the local system is down.  Defaults to false.
.IP "\fBbfd_params : check_tnl_key\fR: optional string, either \fBtrue\fR or \fBfalse\fR"
Set to true to make BFD accept only control messages with a tunnel
key of zero.  By default, BFD accepts control messages with any
tunnel key.
.ST "BFD Status:"
The VTEP sets key-value pairs in the \fBbfd_status\fR
column to report the status of BFD on this tunnel.  When BFD is
not enabled, with \fBbfd_params:enable\fR, the
HSC clears all key-value pairs from \fBbfd_status\fR\.
.IP "\fBbfd_status : state\fR: optional string, one of \fBdown\fR, \fBinit\fR, \fBup\fR, or \fBadmin_down\fR"
Reports the state of the BFD session.  The BFD session is fully
healthy and negotiated if \fBUP\fR\.
.IP "\fBbfd_status : forwarding\fR: optional string, either \fBtrue\fR or \fBfalse\fR"
Reports whether the BFD session believes this tunnel
may be used to forward traffic.  Typically this means the local session
is signaling \fBUP\fR, and the remote system isn\(cqt signaling a
problem such as concatenated path down.
.IP "\fBbfd_status : diagnostic\fR: optional string"
In case of a problem, set to a short message that reports what the
local BFD session thinks is wrong.
.IP "\fBbfd_status : remote_state\fR: optional string, one of \fBdown\fR, \fBinit\fR, \fBup\fR, or \fBadmin_down\fR"
Reports the state of the remote endpoint\(cqs BFD session.
.IP "\fBbfd_status : remote_diagnostic\fR: optional string"
In case of a problem, set to a short message that reports what the
remote endpoint\(cqs BFD session thinks is wrong.
.bp
.SH "Physical_Port TABLE"
A port within a \fBPhysical_Switch\fR\.
.SS "Summary:
.TQ 3.00in
\fBvlan_bindings\fR
map of integer-\fBLogical_Switch\fR pairs, key in range 0 to 4,095
.TQ 3.00in
\fBvlan_stats\fR
map of integer-\fBLogical_Binding_Stats\fR pairs, key in range 0 to 4,095
.TQ .25in
\fIIdentification:\fR
.RS .25in
.TQ 2.75in
\fBname\fR
string
.TQ 2.75in
\fBdescription\fR
string
.RE
.TQ .25in
\fIError Notification:\fR
.RS .25in
.TQ 2.75in
\fBport_fault_status : invalid_vlan_map\fR
none
.TQ 2.75in
\fBport_fault_status : unspecified_fault\fR
none
.RE
.SS "Details:
.IP "\fBvlan_bindings\fR: map of integer-\fBLogical_Switch\fR pairs, key in range 0 to 4,095"
Identifies how VLANs on the physical port are bound to logical switches.
If, for example, the map contains a (VLAN, logical switch) pair, a packet
that arrives on the port in the VLAN is considered to belong to the
paired logical switch.
.IP "\fBvlan_stats\fR: map of integer-\fBLogical_Binding_Stats\fR pairs, key in range 0 to 4,095"
Statistics for VLANs bound to logical switches on the physical port.  An
implementation that fully supports such statistics would populate this
column with a mapping for every VLAN that is bound in \fBvlan_bindings\fR\.  An implementation that does not support such
statistics or only partially supports them would not populate this column
or partially populate it, respectively.
.ST "Identification:"
.IP "\fBname\fR: string"
Symbolic name for the port.  The name ought to be unique within a given
\fBPhysical_Switch\fR, but the database is not capable of
enforcing this.
.IP "\fBdescription\fR: string"
An extended description for the port.
.ST "Error Notification:"
An entry in this column indicates to the NVC that the physical port has
encountered a fault. The switch must clear this column when the errror
has been cleared.
.IP "\fBport_fault_status : invalid_vlan_map\fR: none"
Indicates that a VLAN-to-logical-switch mapping requested by
the controller could not be instantiated by the switch
because of a conflict with local configuration.
.IP "\fBport_fault_status : unspecified_fault\fR: none"
Indicates that an error has occurred on the port but that no
more specific information is available.
.bp
.SH "Logical_Binding_Stats TABLE"
Reports statistics for the \fBLogical_Switch\fR with which a VLAN
on a \fBPhysical_Port\fR is associated.
.SS "Summary:
.TQ .25in
\fIStatistics:\fR
.RS .25in
.TQ 2.75in
\fBpackets_from_local\fR
integer
.TQ 2.75in
\fBbytes_from_local\fR
integer
.TQ 2.75in
\fBpackets_to_local\fR
integer
.TQ 2.75in
\fBbytes_to_local\fR
integer
.RE
.SS "Details:
.ST "Statistics:"
These statistics count only packets to which the binding applies.
.IP "\fBpackets_from_local\fR: integer"
Number of packets sent by the \fBPhysical_Switch\fR\.
.IP "\fBbytes_from_local\fR: integer"
Number of bytes in packets sent by the \fBPhysical_Switch\fR\.
.IP "\fBpackets_to_local\fR: integer"
Number of packets received by the \fBPhysical_Switch\fR\.
.IP "\fBbytes_to_local\fR: integer"
Number of bytes in packets received by the \fBPhysical_Switch\fR\.
.bp
.SH "Logical_Switch TABLE"
A logical Ethernet switch, whose implementation may span physical and
virtual media, possibly crossing L3 domains via tunnels; a logical layer\-2
domain; an Ethernet broadcast domain.
.SS "Summary:
.TQ .25in
\fIPer Logical-Switch Tunnel Key:\fR
.RS .25in
.TQ 2.75in
\fBtunnel_key\fR
optional integer
.RE
.TQ .25in
\fIIdentification:\fR
.RS .25in
.TQ 2.75in
\fBname\fR
string (must be unique within table)
.TQ 2.75in
\fBdescription\fR
string
.RE
.SS "Details:
.ST "Per Logical-Switch Tunnel Key:"
Tunnel protocols tend to have a field that allows the tunnel
to be partitioned into sub-tunnels: VXLAN has a VNI, GRE and
STT have a key, CAPWAP has a WSI, and so on.  We call these
generically ``tunnel keys.\(cq\(cq  Given that one needs to use a
tunnel key at all, there are at least two reasonable ways to
assign their values:
.RS
.IP \(bu
Per \fBLogical_Switch\fR+\fBPhysical_Locator\fR
pair.  That is, each logical switch may be assigned a different
tunnel key on every \fBPhysical_Locator\fR\.  This model is
especially flexible.
.IP
In this model, \fBPhysical_Locator\fR carries the tunnel
key.  Therefore, one \fBPhysical_Locator\fR record will
exist for each logical switch carried at a given IP destination.
.IP \(bu
Per \fBLogical_Switch\fR\.  That is, every tunnel
associated with a particular logical switch carries the same tunnel
key, regardless of the \fBPhysical_Locator\fR to which the
tunnel is addressed.  This model may ease switch implementation
because it imposes fewer requirements on the hardware datapath.
.IP
In this model, \fBLogical_Switch\fR carries the tunnel
key.  Therefore, one \fBPhysical_Locator\fR record will
exist for each IP destination.
.RE
.IP "\fBtunnel_key\fR: optional integer"
This column is used only in the tunnel key per \fBLogical_Switch\fR model (see above), because only in that
model is there a tunnel key associated with a logical switch.
.IP
For \fBvxlan_over_ipv4\fR encapsulation, this column
is the VXLAN VNI that identifies a logical switch.  It must
be in the range 0 to 16,777,215.
.ST "Identification:"
.IP "\fBname\fR: string (must be unique within table)"
Symbolic name for the logical switch.
.IP "\fBdescription\fR: string"
An extended description for the logical switch, such as its switch
login banner.
.bp
.SH "Ucast_Macs_Local TABLE"
Mapping of unicast MAC addresses to tunnels (physical
locators). This table is written by the HSC, so it contains the
MAC addresses that have been learned on physical ports by a
VTEP.
.SS "Summary:
.TQ 3.00in
\fBMAC\fR
string
.TQ 3.00in
\fBlogical_switch\fR
\fBLogical_Switch\fR
.TQ 3.00in
\fBlocator\fR
\fBPhysical_Locator\fR
.TQ 3.00in
\fBipaddr\fR
string
.SS "Details:
.IP "\fBMAC\fR: string"
A MAC address that has been learned by the VTEP.
.IP "\fBlogical_switch\fR: \fBLogical_Switch\fR"
The Logical switch to which this mapping applies.
.IP "\fBlocator\fR: \fBPhysical_Locator\fR"
The physical locator to be used to reach this MAC address. In
this table, the physical locator will be one of the tunnel IP
addresses of the appropriate VTEP.
.IP "\fBipaddr\fR: string"
The IP address to which this MAC corresponds. Optional field for
the purpose of ARP supression.
.bp
.SH "Ucast_Macs_Remote TABLE"
Mapping of unicast MAC addresses to tunnels (physical
locators). This table is written by the NVC, so it contains the
MAC addresses that the NVC has learned. These include VM MAC
addresses, in which case the physical locators will be
hypervisor IP addresses. The NVC will also report MACs that it
has learned from other HSCs in the network, in which case the
physical locators will be tunnel IP addresses of the
corresponding VTEPs.
.SS "Summary:
.TQ 3.00in
\fBMAC\fR
string
.TQ 3.00in
\fBlogical_switch\fR
\fBLogical_Switch\fR
.TQ 3.00in
\fBlocator\fR
\fBPhysical_Locator\fR
.TQ 3.00in
\fBipaddr\fR
string
.SS "Details:
.IP "\fBMAC\fR: string"
A MAC address that has been learned by the NVC.
.IP "\fBlogical_switch\fR: \fBLogical_Switch\fR"
The Logical switch to which this mapping applies.
.IP "\fBlocator\fR: \fBPhysical_Locator\fR"
The physical locator to be used to reach this MAC address. In
this table, the physical locator will be either a hypervisor IP
address or a tunnel IP addresses of another VTEP.
.IP "\fBipaddr\fR: string"
The IP address to which this MAC corresponds. Optional field for
the purpose of ARP supression.
.bp
.SH "Mcast_Macs_Local TABLE"
Mapping of multicast MAC addresses to tunnels (physical
locators). This table is written by the HSC, so it contains the
MAC addresses that have been learned on physical ports by a
VTEP. These may be learned by IGMP snooping, for example. This
table also specifies how to handle unknown unicast and broadcast packets.
.SS "Summary:
.TQ 3.00in
\fBMAC\fR
string
.TQ 3.00in
\fBlogical_switch\fR
\fBLogical_Switch\fR
.TQ 3.00in
\fBlocator_set\fR
\fBPhysical_Locator_Set\fR
.SS "Details:
.IP "\fBMAC\fR: string"
A MAC address that has been learned by the VTEP.
.IP
The keyword \fBunknown\-dst\fR is used as a special
``Ethernet address\(cq\(cq that indicates the locations to which
packets in a logical switch whose destination addresses do not
otherwise appear in \fBUcast_Macs_Local\fR (for
unicast addresses) or \fBMcast_Macs_Local\fR (for
multicast addresses) should be sent.
.IP "\fBlogical_switch\fR: \fBLogical_Switch\fR"
The Logical switch to which this mapping applies.
.IP "\fBlocator_set\fR: \fBPhysical_Locator_Set\fR"
The physical locator set to be used to reach this MAC address. In
this table, the physical locator set will be contain one or more tunnel IP
addresses of the appropriate VTEP(s).
.bp
.SH "Mcast_Macs_Remote TABLE"
Mapping of multicast MAC addresses to tunnels (physical
locators). This table is written by the NVC, so it contains the
MAC addresses that the NVC has learned. This
table also specifies how to handle unknown unicast and broadcast
packets.
.PP
Multicast packet replication may be handled by a service node,
in which case the physical locators will be IP addresses of
service nodes. If the VTEP supports replication onto multiple
tunnels, then this may be used to replicate directly onto
VTEP-hyperisor tunnels.
.SS "Summary:
.TQ 3.00in
\fBMAC\fR
string
.TQ 3.00in
\fBlogical_switch\fR
\fBLogical_Switch\fR
.TQ 3.00in
\fBlocator_set\fR
\fBPhysical_Locator_Set\fR
.TQ 3.00in
\fBipaddr\fR
string
.SS "Details:
.IP "\fBMAC\fR: string"
A MAC address that has been learned by the NVC.
.IP
The keyword \fBunknown\-dst\fR is used as a special
``Ethernet address\(cq\(cq that indicates the locations to which
packets in a logical switch whose destination addresses do not
otherwise appear in \fBUcast_Macs_Remote\fR (for
unicast addresses) or \fBMcast_Macs_Remote\fR (for
multicast addresses) should be sent.
.IP "\fBlogical_switch\fR: \fBLogical_Switch\fR"
The Logical switch to which this mapping applies.
.IP "\fBlocator_set\fR: \fBPhysical_Locator_Set\fR"
The physical locator set to be used to reach this MAC address. In
this table, the physical locator set will be either a service node IP
address or a set of tunnel IP addresses of hypervisors (and
potentially other VTEPs).
.IP "\fBipaddr\fR: string"
The IP address to which this MAC corresponds. Optional field for
the purpose of ARP supression.
.bp
.SH "Logical_Router TABLE"
A logical router, or VRF. A logical router may be connected to one or more
logical switches. Subnet addresses and interface addresses may be configured on the
interfaces.
.SS "Summary:
.TQ 3.00in
\fBswitch_binding\fR
map of string-\fBLogical_Switch\fR pairs
.TQ 3.00in
\fBstatic_routes\fR
map of string-string pairs
.TQ .25in
\fIIdentification:\fR
.RS .25in
.TQ 2.75in
\fBname\fR
string (must be unique within table)
.TQ 2.75in
\fBdescription\fR
string
.RE
.SS "Details:
.IP "\fBswitch_binding\fR: map of string-\fBLogical_Switch\fR pairs"
Maps from an IPv4 or IPv6 address prefix in CIDR notation to a
logical switch. Multiple prefixes may map to the same switch. By
writing a 32-bit (or 128-bit for v6) address with a /N prefix
length, both the router\(cqs interface address and the subnet
prefix can be configured. For example, 192.68.1.1/24 creates a
/24 subnet for the logical switch attached to the interface and
assigns the address 192.68.1.1 to the router interface.
.IP "\fBstatic_routes\fR: map of string-string pairs"
One or more static routes, mapping IP prefixes to next hop IP addresses.
.ST "Identification:"
.IP "\fBname\fR: string (must be unique within table)"
Symbolic name for the logical router.
.IP "\fBdescription\fR: string"
An extended description for the logical router.
.bp
.SH "Arp_Sources_Local TABLE"
MAC address to be used when a VTEP issues ARP requests on behalf
of a logical router.
.PP
A distributed logical router is implemented by a set of VTEPs
(both hardware VTEPs and vswitches). In order for a given VTEP
to populate the local ARP cache for a logical router, it issues
ARP requests with a source MAC address that is unique to the VTEP. A
single per-VTEP MAC can be re-used across all logical
networks. This table contains the MACs that are used by the
VTEPs of a given HSC. The table provides the mapping from MAC to
physical locator for each VTEP so that replies to the ARP
requests can be sent back to the correct VTEP using the
appropriate physical locator.
.SS "Summary:
.TQ 3.00in
\fBsrc_mac\fR
string
.TQ 3.00in
\fBlocator\fR
\fBPhysical_Locator\fR
.SS "Details:
.IP "\fBsrc_mac\fR: string"
The source MAC to be used by a given VTEP.
.IP "\fBlocator\fR: \fBPhysical_Locator\fR"
The \fBPhysical_Locator\fR to use for replies to ARP
requests from this MAC address.
.bp
.SH "Arp_Sources_Remote TABLE"
MAC address to be used when a remote VTEP issues ARP requests on behalf
of a logical router.
.PP
This table is the remote counterpart of \fBArp_sources_local\fR\. The NVC writes this table to notify
the HSC of the MACs that will be used by remote VTEPs when they
issue ARP requests on behalf of a distributed logical router.
.SS "Summary:
.TQ 3.00in
\fBsrc_mac\fR
string
.TQ 3.00in
\fBlocator\fR
\fBPhysical_Locator\fR
.SS "Details:
.IP "\fBsrc_mac\fR: string"
The source MAC to be used by a given VTEP.
.IP "\fBlocator\fR: \fBPhysical_Locator\fR"
The \fBPhysical_Locator\fR to use for replies to ARP
requests from this MAC address.
.bp
.SH "Physical_Locator_Set TABLE"
A set of one or more \fBPhysical_Locator\fRs.
.PP
This table exists only because OVSDB does not have a way to
express the type ``map from string to one or more \fBPhysical_Locator\fR records.\(cq\(cq
.SS "Summary:
.TQ 3.00in
\fBlocators\fR
immutable set of 1 or more \fBPhysical_Locator\fRs
.SS "Details:
.IP "\fBlocators\fR: immutable set of 1 or more \fBPhysical_Locator\fRs"
.bp
.SH "Physical_Locator TABLE"
Identifies an endpoint to which logical switch traffic may be
encapsulated and forwarded.
.PP
For the \fBvxlan_over_ipv4\fR encapsulation, the only
encapsulation defined so far, all endpoints associated with a given \fBLogical_Switch\fR must use a common tunnel key, which is carried
in the \fBtunnel_key\fR column of \fBLogical_Switch\fR\.
.PP
For some encapsulations yet to be defined, we expect \fBPhysical_Locator\fR to identify both an endpoint and a tunnel key.
When the first such encapsulation is defined, we expect to add a
``tunnel_key\(cq\(cq column to \fBPhysical_Locator\fR to allow the
tunnel key to be defined.
.PP
See the ``Per Logical-Switch Tunnel Key\(cq\(cq section in the \fBLogical_Switch\fR table for further discussion of the model.
.SS "Summary:
.TQ 3.00in
\fBencapsulation_type\fR
immutable string, must be \fBvxlan_over_ipv4\fR
.TQ 3.00in
\fBdst_ip\fR
immutable string
.SS "Details:
.IP "\fBencapsulation_type\fR: immutable string, must be \fBvxlan_over_ipv4\fR"
The type of tunneling encapsulation.
.IP "\fBdst_ip\fR: immutable string"
For \fBvxlan_over_ipv4\fR encapsulation, the IPv4 address of the
VXLAN tunnel endpoint.
.IP
We expect that this column could be used for IPv4 or IPv6 addresses in
encapsulations to be introduced later.
